name: llm_quant_attack
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asttokens==3.0.0
      - attrs==25.4.0
      - bitarray==3.7.2
      - bitsandbytes==0.49.0
      - boto3==1.42.14
      - botocore==1.42.14
      - certifi==2025.10.5
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - dataproperty==1.1.0
      - datasets==2.21.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - dill==0.3.8
      - distro==1.9.0
      - einops==0.8.1
      - evaluate==0.4.6
      - executing==2.2.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2024.6.1
      - gguf==0.17.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - hqq==0.2.8.post1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - inquirerpy==0.3.4
      - ipykernel==7.1.0
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.11.1
      - jmespath==1.0.1
      - joblib==1.5.3
      - jsonlines==4.0.0
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - libcst==1.8.5
      - lm-eval==0.4.9.2
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mbstrdecoder==1.1.4
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nltk==3.9.2
      - numexpr==2.14.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.6.1
      - optimum==2.0.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pathvalidate==3.3.1
      - peft==0.17.1
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==12.0.0
      - platformdirs==4.5.0
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pybind11==3.0.1
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytablewriter==1.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - q-attack==0.0.1
      - regex==2025.10.23
      - requests==2.32.5
      - rich==14.2.0
      - rouge-score==0.1.2
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - s3transfer==0.16.0
      - sacrebleu==2.5.1
      - safecoder==0.0.1
      - safetensors==0.6.2
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - sqlitedict==2.1.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - tqdm-multiprocess==0.0.11
      - traitlets==5.14.3
      - transformers==4.57.3
      - triton==3.5.0
      - trl==0.15.2
      - typepy==1.3.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - word2number==1.1
      - xxhash==3.6.0
      - yamlize==0.7.1
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /home/ubuntu/dhs/miniconda3/envs/llm_quant_attack
